feat: add users and schedule data
firehydrant/terraform-provider-firehydrant pull request #109
Opened 2022-10-11 04:44 UTC by DerekTBrown

This PR adds two new data providers; `user` and `schedule`.  These are a pre-requisite to be able to implement #17.

2022-10-11 04:45 UTC, DerekTBrown commented on provider/user_data_test.go
> +						"data.firehydrant_user.test_user", "email", "test-user@firehydrant.io"),
I would appreciate some advice on how best to test these new data sources. The existing `data` modules all seem to be tested in conjunction with a `resource` module.  To test this, I would need to introduce mocks, which don't seem to exist in this repository.

2022-11-29 01:27 UTC, nearbycoder requested changes
Hey Derek,

Appreciate the work that you have done here to add users and schedule data to the provider. Apologies for the late reply. I have taken the time to test this out and below are what I have found.

Overall this is looking good there was just a few issues that I had found when trying to run this locally that will need to be cleaned up.

Additionally for this to work properly you will need to add the DataSources to the DataSourcesMap within [provider.go](https://github.com/firehydrant/terraform-provider-firehydrant/blob/main/provider/provider.go#L68)

```go
"firehydrant_schedule":       dataSourceSchedule(),
"firehydrant_user":           dataSourceUser(),
```

As far as testing goes this is an interesting circumstance as we usually have a `resource` in order to create, to test against. I will get back to you with an answer on that, hopefully tomorrow after I consult with my team.

2022-11-29 01:27 UTC, nearbycoder commented on provider/user_data.go
> +		ReadContext: dataFireHydrantPriority,
This will need to be `dataFireHydrantUser`
```suggestion
		ReadContext: dataFireHydrantUser,
```

2022-11-29 01:27 UTC, nearbycoder commented on firehydrant/types.go
> +	SlackLinked string    `json:"slack_linked?"`
this will need to be a bool
```suggestion
	SlackLinked bool    `json:"slack_linked?"`
```

2022-11-29 01:27 UTC, nearbycoder commented on provider/user_data.go
> +		"id": email,
Update to include the name of what the value is.

```suggestion
		"email": email,
```

2022-11-30 21:59 UTC, DerekTBrown commented
@nearbycoder I have applied the requested fixes. Let me know how I should go about adding tests for this!

2022-11-30 22:02 UTC, nearbycoder commented
> @nearbycoder I have applied the requested fixes. Let me know how I should go about adding tests for this!

for sure, I was just about to post something about that.

it's a bit hacky but I was able to create a mock server requests to fake out the calls at least for this request. Still needs to be fleshed out with testing all the properties but I think this may assist you

```golang
func TestUserDataSource_basic(t *testing.T) {

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

		if r.URL.Path != "/ping" && r.URL.Path != "/users" {
			t.Errorf("Expected to request '/ping' or '/users', got: %s", r.URL.Path)
		}

		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"data":[{"id": "123", "email":"test-user@firehydrant.io"}]}`))
	}))

	defer server.Close()

	orig := os.Getenv("FIREHYDRANT_BASE_URL")
	os.Setenv("FIREHYDRANT_BASE_URL", server.URL)
	t.Cleanup(func() { os.Setenv("FIREHYDRANT_BASE_URL", orig) })

	resource.Test(t, resource.TestCase{
		PreCheck:          func() { testFireHydrantIsSetup(t) },
		ProviderFactories: defaultProviderFactories(),
		Steps: []resource.TestStep{
			{
				Config: testUserDataSourceConfig_basic(),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("data.firehydrant_user.test_user", "id"),
					resource.TestCheckResourceAttr(
						"data.firehydrant_user.test_user", "email", "test-user@firehydrant.io"),
				),
			},
		},
	})
}
```

let me know if you have any other questions! We appreciate the contributions!

2022-12-03 00:48 UTC, DerekTBrown commented
@nearbycoder could you grant me approval to run the test workflow?

2022-12-03 01:08 UTC, DerekTBrown commented
@nearbycoder I believe the PR should be close to ready to go.

I don't have a good way of running the tests iteratively (running locally requires a test API key, running on Github seems to require approval each time I want to run). 

What is the next step?

2022-12-03 01:15 UTC, nearbycoder commented
> @nearbycoder I believe the PR should be close to ready to go.
> 
> 
> 
> I don't have a good way of running the tests iteratively (running locally requires a test API key, running on Github seems to require approval each time I want to run). 
> 
> 
> 
> What is the next step? 

@DerekTBrown I agree it's pretty much there I can button up the rest and ensure the specs are passing. Apologize we have some work today to make this more friendly to outside contributors. Will get this merged in on Monday and look at getting a new release out. Additionally will consult with our engineering group about improving the contribution path.

2022-12-07 02:50 UTC, merged